import { Offer } from '../types/offer.types';
import { ReviewType } from '../types/review.types';

export const OFFERS: { [offesrId: number]: Offer } = {
  1: {
    city: {
      name: 'Cologne',
      location: {
        latitude: 50.938361,
        longitude: 6.959974,
        zoom: 13,
      },
    },
    previewImage: 'https://9.react.pages.academy/static/hotel/13.jpg',
    images: [
      'https://9.react.pages.academy/static/hotel/18.jpg',
      'https://9.react.pages.academy/static/hotel/14.jpg',
      'https://9.react.pages.academy/static/hotel/16.jpg',
      'https://9.react.pages.academy/static/hotel/8.jpg',
      'https://9.react.pages.academy/static/hotel/3.jpg',
      'https://9.react.pages.academy/static/hotel/12.jpg',
      'https://9.react.pages.academy/static/hotel/17.jpg',
      'https://9.react.pages.academy/static/hotel/6.jpg',
      'https://9.react.pages.academy/static/hotel/13.jpg',
      'https://9.react.pages.academy/static/hotel/9.jpg',
      'https://9.react.pages.academy/static/hotel/10.jpg',
      'https://9.react.pages.academy/static/hotel/20.jpg',
      'https://9.react.pages.academy/static/hotel/7.jpg',
      'https://9.react.pages.academy/static/hotel/5.jpg',
    ],
    title: 'The house among olive ',
    isFavorite: false,
    isPremium: true,
    rating: 3.5,
    type: 'house',
    bedrooms: 4,
    maxAdults: 6,
    price: 154,
    goods: [
      'Coffee machine',
      'Breakfast',
      'Laptop friendly workspace',
      'Fridge',
      'Baby seat',
      'Air conditioning',
      'Washer',
      'Towels',
      'Washing machine',
      'Dishwasher',
    ],
    host: {
      id: 25,
      name: 'Angelina',
      isPro: true,
      avatarUrl: 'img/avatar-angelina.jpg',
    },
    description: 'I am happy to welcome you to my apartment in the city center! Three words: location, cosy and chic!',
    location: {
      latitude: 50.916361,
      longitude: 6.944974,
      zoom: 16,
    },
    id: 1,
  },
  2: {
    city: {
      name: 'Paris',
      location: {
        latitude: 48.85661,
        longitude: 2.351499,
        zoom: 13,
      },
    },
    previewImage: 'https://9.react.pages.academy/static/hotel/13.jpg',
    images: [
      'https://9.react.pages.academy/static/hotel/12.jpg',
      'https://9.react.pages.academy/static/hotel/5.jpg',
      'https://9.react.pages.academy/static/hotel/13.jpg',
      'https://9.react.pages.academy/static/hotel/7.jpg',
      'https://9.react.pages.academy/static/hotel/20.jpg',
      'https://9.react.pages.academy/static/hotel/6.jpg',
      'https://9.react.pages.academy/static/hotel/11.jpg',
      'https://9.react.pages.academy/static/hotel/16.jpg',
      'https://9.react.pages.academy/static/hotel/15.jpg',
      'https://9.react.pages.academy/static/hotel/14.jpg',
      'https://9.react.pages.academy/static/hotel/4.jpg',
      'https://9.react.pages.academy/static/hotel/10.jpg',
      'https://9.react.pages.academy/static/hotel/1.jpg',
      'https://9.react.pages.academy/static/hotel/2.jpg',
    ],
    title: 'Tile House',
    isFavorite: false,
    isPremium: false,
    rating: 3.8,
    type: 'apartment',
    bedrooms: 1,
    maxAdults: 1,
    price: 238,
    goods: [
      'Breakfast',
      'Laptop friendly workspace',
      'Washer',
      'Baby seat',
      'Air conditioning',
    ],
    host: {
      'id': 25,
      'name': 'Angelina',
      'isPro': true,
      'avatarUrl': 'img/avatar-angelina.jpg',
    },
    description: 'A new spacious villa, one floor. All commodities, jacuzzi and beautiful scenery. Ideal for families or friends.',
    location: {
      'latitude': 48.843610000000005,
      'longitude': 2.338499,
      'zoom': 16,
    },
    id: 2,
  },
  3: {
    city: {
      name: 'Hamburg',
      location: {
        'latitude': 53.550341,
        'longitude': 10.000654,
        'zoom': 13,
      },
    },
    previewImage: 'https://9.react.pages.academy/static/hotel/9.jpg',
    images: [
      'https://9.react.pages.academy/static/hotel/19.jpg',
      'https://9.react.pages.academy/static/hotel/7.jpg',
      'https://9.react.pages.academy/static/hotel/3.jpg',
      'https://9.react.pages.academy/static/hotel/2.jpg',
      'https://9.react.pages.academy/static/hotel/4.jpg',
      'https://9.react.pages.academy/static/hotel/11.jpg',
      'https://9.react.pages.academy/static/hotel/5.jpg',
      'https://9.react.pages.academy/static/hotel/15.jpg',
      'https://9.react.pages.academy/static/hotel/8.jpg',
      'https://9.react.pages.academy/static/hotel/12.jpg',
      'https://9.react.pages.academy/static/hotel/18.jpg',
      'https://9.react.pages.academy/static/hotel/13.jpg',
      'https://9.react.pages.academy/static/hotel/10.jpg',
      'https://9.react.pages.academy/static/hotel/9.jpg',
    ],
    title: 'House in countryside',
    isFavorite: false,
    isPremium: false,
    rating: 4,
    type: 'room',
    bedrooms: 1,
    maxAdults: 2,
    price: 123,
    goods: [
      'Laptop friendly workspace',
      'Washer',
      'Towels',
      'Baby seat',
      'Air conditioning',
      'Breakfast',
      'Fridge',
    ],
    host: {
      id: 25,
      name: 'Angelina',
      isPro: true,
      avatarUrl: 'img/avatar-angelina.jpg',
    },
    description: 'I am happy to welcome you to my apartment in the city center! Three words: location, cosy and chic!',
    location: {
      latitude: 53.529341,
      longitude: 9.975654,
      zoom: 16,
    },
    id: 3,
  },
};

export const OFFER: Offer = {
  city: {
    name: 'Cologne',
    location: {
      latitude: 50.938361,
      longitude: 6.959974,
      zoom: 13,
    },
  },
  previewImage: 'https://9.react.pages.academy/static/hotel/13.jpg',
  images: [
    'https://9.react.pages.academy/static/hotel/18.jpg',
    'https://9.react.pages.academy/static/hotel/14.jpg',
    'https://9.react.pages.academy/static/hotel/16.jpg',
    'https://9.react.pages.academy/static/hotel/8.jpg',
    'https://9.react.pages.academy/static/hotel/3.jpg',
    'https://9.react.pages.academy/static/hotel/12.jpg',
    'https://9.react.pages.academy/static/hotel/17.jpg',
    'https://9.react.pages.academy/static/hotel/6.jpg',
    'https://9.react.pages.academy/static/hotel/13.jpg',
    'https://9.react.pages.academy/static/hotel/9.jpg',
    'https://9.react.pages.academy/static/hotel/10.jpg',
    'https://9.react.pages.academy/static/hotel/20.jpg',
    'https://9.react.pages.academy/static/hotel/7.jpg',
    'https://9.react.pages.academy/static/hotel/5.jpg',
  ],
  title: 'The house among olive ',
  isFavorite: true,
  isPremium: false,
  rating: 3.5,
  type: 'house',
  bedrooms: 4,
  maxAdults: 6,
  price: 154,
  goods: [
    'Coffee machine',
    'Breakfast',
    'Laptop friendly workspace',
    'Fridge',
    'Baby seat',
    'Air conditioning',
    'Washer',
    'Towels',
    'Washing machine',
    'Dishwasher',
  ],
  host: {
    id: 25,
    name: 'Angelina',
    isPro: true,
    avatarUrl: 'img/avatar-angelina.jpg',
  },
  description: 'I am happy to welcome you to my apartment in the city center! Three words: location, cosy and chic!',
  location: {
    latitude: 50.916361,
    longitude: 6.944974,
    zoom: 16,
  },
  id: 1,
};

export const REVIEWS: ReviewType[] = [
  {
    id: 1,
    user: {
      id: 13,
      isPro: false,
      name: 'Zak',
      avatarUrl: 'https://9.react.pages.academy/static/avatar/4.jpg',
    },
    rating: 3,
    comment: 'This villa is perfect in every way: the view on mountains and waterfalls, the hot tub and the villa itself. The evening here became a great continuation of our journeys over country.',
    date: '2022-01-31T15:13:26.370Z',
  },
  {
    id: 2,
    user: {
      id: 16,
      isPro: true,
      name: 'Mollie',
      avatarUrl: 'https://9.react.pages.academy/static/avatar/7.jpg',
    },
    rating: 4,
    comment: 'Home is amazing. It\'s like staying in a museum. The rooms, furnishings and artworks are incredible. The views of My Vesuvius',
    date: '2022-01-31T15:13:26.370Z',
  },
];
